export const airlineData = [
  {
    name: 'Abelag',
    years: ' (1964-)',
    country: 'Belgium',
    wiki: '/wiki/Abelag',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Abelag_logo.jpg',
    file: 'abelag.jpg',
  },
  {
    name: 'Brussels Airlines',
    years: ' (2006-)',
    country: 'Belgium',
    wiki: '/wiki/Brussels_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Brussels_airlines_logo_2021.svg',
    file: 'brussels-airlines.svg',
  },
  {
    name: 'Koninklijke Luchtvaart Maatschappij',
    years: ' (KLM)',
    country: 'Netherlands',
    wiki: '/wiki/Koninklijke_Luchtvaart_Maatschappij',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/KLM_logo.svg',
    file: 'koninklijke-luchtvaart-maatschappij.svg',
  },
  {
    name: 'Transavia',
    years: '',
    country: 'Netherlands',
    wiki: '/wiki/Transavia_(Nederland)',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Transavia_logo.svg',
    file: 'transavia.svg',
  },
  {
    name: 'Divi Divi Air',
    years: '',
    country: 'Netherlands',
    wiki: '/wiki/Divi_Divi_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Divi_Divi_Air_logo.jpg',
    file: 'divi-divi-air.jpg',
  },
  {
    name: 'Fly All Ways',
    years: '',
    country: 'Suriname',
    wiki: '/wiki/Fly_All_Ways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Flyallways_logo.jpg',
    file: 'fly-all-ways.jpg',
  },
  {
    name: 'Gum Air',
    years: '',
    country: 'Suriname',
    wiki: '/wiki/Gum_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Gum_air_logo.svg',
    file: 'gum-air.svg',
  },
  {
    name: 'Ariana Afghan Airlines',
    years: '',
    country: 'Afghanistan',
    wiki: '/wiki/Ariana_Afghan_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Ariana_Afghan_Airlines_logo.svg',
    file: 'ariana-afghan-airlines.svg',
  },
  {
    name: 'LAN Argentina',
    years: '',
    country: 'Argentina',
    wiki: '/wiki/LAN_Argentina',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Latam-logo_-v_%28Indigo%29.svg',
    file: 'lan-argentina.svg',
  },
  {
    name: 'Air Armenia',
    years: '',
    country: 'Armenia',
    wiki: '/wiki/Air_Armenia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Air_Armenia_logo.svg',
    file: 'air-armenia.svg',
  },
  {
    name: 'Airlines of Tasmania',
    years: '',
    country: 'Australia',
    wiki: '/wiki/Airlines_of_Tasmania',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Airlines_of_Tasmania_logo.svg',
    file: 'airlines-of-tasmania.svg',
  },
  {
    name: 'Jetstar Airways',
    years: '',
    country: 'Australia',
    wiki: '/wiki/Jetstar_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Jetstar_logo.svg',
    file: 'jetstar-airways.svg',
  },
  {
    name: 'Virgin Australia',
    years: '',
    country: 'Australia',
    wiki: '/wiki/Virgin_Australia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Virgin-logo.svg',
    file: 'virgin-australia.svg',
  },
  {
    name: 'LATAM',
    years: '',
    country: 'Brazil',
    wiki: '/wiki/LATAM',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Latam-logo_-v_%28Indigo%29.svg',
    file: 'latam.svg',
  },
  {
    name: 'Air Canada',
    years: '',
    country: 'Canada',
    wiki: '/wiki/Air_Canada',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Air_Canada_logo.svg',
    file: 'air-canada.svg',
  },
  {
    name: 'Air Canada Jazz',
    years: '',
    country: 'Canada',
    wiki: '/wiki/Air_Canada_Jazz',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/29/Jazz_Aviation_logo.svg',
    file: 'air-canada-jazz.svg',
  },
  {
    name: 'Air Transat',
    years: '',
    country: 'Canada',
    wiki: '/wiki/Air_Transat',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Air_Transat_logo.svg',
    file: 'air-transat.svg',
  },
  {
    name: 'Air Kasaï',
    years: '',
    country: 'Congo, Democratic Republic',
    wiki: '/wiki/Air_Kasa%C3%AF',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Air_Kasa%C3%AF_logo.svg',
    file: 'air-kasaï.svg',
  },
  {
    name: 'Volaris Costa Rica',
    years: '',
    country: 'Costa Rica',
    wiki: '/wiki/Volaris_Costa_Rica',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Volaris-logo.svg',
    file: 'volaris-costa-rica.svg',
  },
  {
    name: 'Air Greenland',
    years: '',
    country: 'Denmark',
    wiki: '/wiki/Air_Greenland',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Air_Greenland_logo.svg',
    file: 'air-greenland.svg',
  },
  {
    name: 'Condor Flugdienst',
    years: '',
    country: 'Germany',
    wiki: '/wiki/Condor_Flugdienst',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Condor_logo_2022.svg',
    file: 'condor-flugdienst.svg',
  },
  {
    name: 'Lufthansa Cargo',
    years: '',
    country: 'Germany',
    wiki: '/wiki/Lufthansa_Cargo',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Lufthansa_Cargo_logo_with_claim.svg',
    file: 'lufthansa-cargo.svg',
  },
  {
    name: 'LAN Ecuador',
    years: '',
    country: 'Ecuador',
    wiki: '/wiki/LAN_Ecuador',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Latam-logo_-v_%28Indigo%29.svg',
    file: 'lan-ecuador.svg',
  },
  {
    name: 'LATAM Ecuador',
    years: '',
    country: 'Ecuador',
    wiki: '/wiki/LATAM_Ecuador',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Latam-logo_-v_%28Indigo%29.svg',
    file: 'latam-ecuador.svg',
  },
  {
    name: 'Volaris El Salvador',
    years: '',
    country: 'El Salvador',
    wiki: '/wiki/Volaris_El_Salvador',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Volaris-logo.svg',
    file: 'volaris-el-salvador.svg',
  },
  {
    name: 'Olympic Air',
    years: '',
    country: 'Greece',
    wiki: '/wiki/Olympic_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e1/Olympic_Air_logo.png',
    file: 'olympic-air.png',
  },
  {
    name: 'Travel Service',
    years: '',
    country: 'Hungary',
    wiki: '/wiki/Travel_Service',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Smartwings_logo.svg',
    file: 'travel-service.svg',
  },
  {
    name: 'Wizz Air',
    years: '',
    country: 'Hungary',
    wiki: '/wiki/Wizz_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Wizz_Air_logo_2015.svg',
    file: 'wizz-air.svg',
  },
  {
    name: 'Cityjet',
    years: '',
    country: 'Ireland',
    wiki: '/wiki/Cityjet',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Cityjet_logo.svg',
    file: 'cityjet.svg',
  },
  {
    name: 'Blue Dart Aviation',
    years: '',
    country: 'India',
    wiki: '/wiki/Blue_Dart_Aviation',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Blue_Dart_logo_transparent.png',
    file: 'blue-dart-aviation.png',
  },
  {
    name: 'IndiGo',
    years: '',
    country: 'India',
    wiki: '/wiki/IndiGo',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/69/IndiGo_Airlines_logo.svg',
    file: 'indigo.svg',
  },
  {
    name: 'Arkia Israeli Airlines',
    years: '',
    country: 'Israel',
    wiki: '/wiki/Arkia_Israeli_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Arkia_logo.png',
    file: 'arkia-israeli-airlines.png',
  },
  {
    name: 'Mistral Air',
    years: '',
    country: 'Italy',
    wiki: '/wiki/Mistral_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Poste_Air_Cargo_logo.svg',
    file: 'mistral-air.svg',
  },
  {
    name: 'Oriental Air Bridge',
    years: '',
    country: 'Japan',
    wiki: '/wiki/Oriental_Air_Bridge',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Orclogo3.jpg',
    file: 'oriental-air-bridge.jpg',
  },
  {
    name: 'Jazeera Airways',
    years: '',
    country: 'Kuwait',
    wiki: '/wiki/Jazeera_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6d/Jazeera_Airways_logo.svg',
    file: 'jazeera-airways.svg',
  },
  {
    name: 'AirBaltic',
    years: ' (1995-)',
    country: 'Estonia',
    wiki: '/wiki/AirBaltic',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Airbaltic-logo.png',
    file: 'airbaltic.png',
  },
  {
    name: 'Avion Express',
    years: ' (2005-)',
    country: 'Lithuania',
    wiki: '/wiki/Avion_Express',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Avion-express-logo.png',
    file: 'avion-express.png',
  },
  {
    name: 'KM Malta Airlines',
    years: '',
    country: 'Malta',
    wiki: '/wiki/KM_Malta_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/69/KM_Malta_Airlines_logo.png',
    file: 'km-malta-airlines.png',
  },
  {
    name: 'Volaris',
    years: '',
    country: 'Mexico',
    wiki: '/wiki/Volaris',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Volaris-logo.svg',
    file: 'volaris.svg',
  },
  {
    name: 'Air New Zealand',
    years: '',
    country: 'New Zealand',
    wiki: '/wiki/Air_New_Zealand',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/97/Air_New_Zealand_logo.svg',
    file: 'air-new-zealand.svg',
  },
  {
    name: 'Dniproavia',
    years: '',
    country: 'Ukraine',
    wiki: '/wiki/Dniproavia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ef/Dniproawialogo.png',
    file: 'dniproavia.png',
  },
  {
    name: 'Ukraine International Airlines',
    years: '',
    country: 'Ukraine',
    wiki: '/wiki/Ukraine_International_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Ukraine_International_Airlines_logo.svg',
    file: 'ukraine-international-airlines.svg',
  },
  {
    name: 'Copa Airlines',
    years: '',
    country: 'Panama',
    wiki: '/wiki/Copa_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Copa_airlines_logo.png',
    file: 'copa-airlines.png',
  },
  {
    name: 'Air LuxorHi Fly',
    years: 'Air Luxor (tegenwoordig Hi Fly)',
    country: 'Portugal',
    wiki: '/wiki/Air_Luxor',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Air_Luxor_logo.svg',
    file: 'air-luxorhi-fly.svg',
  },
  {
    name: 'Hi Fly',
    years: '',
    country: 'Portugal',
    wiki: '/wiki/Hi_Fly',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Hi_Fly_logo.svg',
    file: 'hi-fly.svg',
  },
  {
    name: 'Qatar Airways',
    years: '',
    country: 'Qatar',
    wiki: '/wiki/Qatar_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/75/Qatar_Airways_logo.svg',
    file: 'qatar-airways.svg',
  },
  {
    name: 'Aeroflot',
    years: '',
    country: 'Russia',
    wiki: '/wiki/Aeroflot',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Aeroflot_Russian_Airlines_logo_%28en%29.svg',
    file: 'aeroflot.svg',
  },
  {
    name: 'Dobrolet Airlines',
    years: '',
    country: 'Russia',
    wiki: '/wiki/Dobrolet_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Dobrolet_logo_%28English%29.png',
    file: 'dobrolet-airlines.png',
  },
  {
    name: 'RusAir',
    years: '',
    country: 'Russia',
    wiki: '/wiki/RusAir',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Rusair_logo.png',
    file: 'rusair.png',
  },
  {
    name: 'Saratov Airlines',
    years: '',
    country: 'Russia',
    wiki: '/wiki/Saratov_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Saratov_Airlines_logo.png',
    file: 'saratov-airlines.png',
  },
  {
    name: 'S7 Airlines',
    years: '',
    country: 'Russia',
    wiki: '/wiki/S7_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/S7_new_logo.svg',
    file: 's7-airlines.svg',
  },
  {
    name: 'Air Nostrum',
    years: '',
    country: 'Spanje',
    wiki: '/wiki/Air_Nostrum',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Air_Nostrum_logo.svg',
    file: 'air-nostrum.svg',
  },
  {
    name: 'Binter Canarias',
    years: '',
    country: 'Spanje',
    wiki: '/wiki/Binter_Canarias',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Binter_logo.svg',
    file: 'binter-canarias.svg',
  },
  {
    name: 'Nok Air',
    years: '',
    country: 'Thailand',
    wiki: '/wiki/Nok_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Nokair_logo.jpg',
    file: 'nok-air.jpg',
  },
  {
    name: 'Smartwings',
    years: '',
    country: 'Tsjechië',
    wiki: '/wiki/Smart_Wings',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Smart-wings-logo.png',
    file: 'smartwings.png',
  },
  {
    name: 'Travel Service',
    years: '',
    country: 'Tsjechië',
    wiki: '/wiki/Travel_Service',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Smartwings_logo.svg',
    file: 'travel-service.svg',
  },
  {
    name: 'IZair',
    years: '',
    country: 'Turkije',
    wiki: '/wiki/IZair',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/71/%C4%B0zmir_Airlines_logo.svg',
    file: 'izair.svg',
  },
  {
    name: 'Pegasus Airlines',
    years: '',
    country: 'Turkije',
    wiki: '/wiki/Pegasus_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Pegasus_Airlines_logo.svg',
    file: 'pegasus-airlines.svg',
  },
  {
    name: 'Turkish Airlines',
    years: '',
    country: 'Turkije',
    wiki: '/wiki/Turkish_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Turkish_Airlines_logo_2019_compact.svg',
    file: 'turkish-airlines.svg',
  },
  {
    name: 'Alas Uruguay',
    years: '',
    country: 'Uruguay',
    wiki: '/wiki/Alas_Uruguay',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Alas_Uruguay_logo.png',
    file: 'alas-uruguay.png',
  },
  {
    name: 'Avensa',
    years: '',
    country: 'Venezuela',
    wiki: '/wiki/Avensa',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Avensa_logo.png',
    file: 'avensa.png',
  },
  {
    name: 'LASER Airlines',
    years: '',
    country: 'Venezuela',
    wiki: '/wiki/LASER_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Laser_%28airline%29_logo.svg',
    file: 'laser-airlines.svg',
  },
  {
    name: 'Emirates',
    years: '',
    country: 'Verenigde Arabische Emiraten',
    wiki: '/wiki/Emirates',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Emirates_logo.svg',
    file: 'emirates.svg',
  },
  {
    name: 'Etihad Airways',
    years: '',
    country: 'Verenigde Arabische Emiraten',
    wiki: '/wiki/Etihad_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0e/Etihad-airways-logo.svg',
    file: 'etihad-airways.svg',
  },
  {
    name: 'Wizz Air Abu Dhabi',
    years: '',
    country: 'Verenigde Arabische Emiraten',
    wiki: '/wiki/Wizz_Air_Abu_Dhabi',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/3/35/Wizz_Air_logo_2015.svg',
    file: 'wizz-air-abu-dhabi.svg',
  },
  {
    name: 'ABX Air',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/ABX_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Abx_Air_logo.svg',
    file: 'abx-air.svg',
  },
  {
    name: 'Alaska Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Alaska_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Alaska_Airlines_logo.svg',
    file: 'alaska-airlines.svg',
  },
  {
    name: 'Allegiant Air',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Allegiant_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/be/Allegiant_Air_logo.svg',
    file: 'allegiant-air.svg',
  },
  {
    name: 'Atlas Air',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Atlas_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/28/Atlas_Air_Worldwide_logo.svg',
    file: 'atlas-air.svg',
  },
  {
    name: 'Delta Air Lines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Delta_Air_Lines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/Delta_logo.svg',
    file: 'delta-air-lines.svg',
  },
  {
    name: 'Frontier Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Frontier_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Frontier_airlines_logo14.svg',
    file: 'frontier-airlines.svg',
  },
  {
    name: 'GoJet Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/GoJet_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/GoJet_logo.gif',
    file: 'gojet-airlines.gif',
  },
  {
    name: 'Hawaiian Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Hawaiian_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Hawaiian_Airlines_logo.png',
    file: 'hawaiian-airlines.png',
  },
  {
    name: 'SkyWest Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/SkyWest_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/45/SkyWest_Airlines_%28United_States%29_logo.svg',
    file: 'skywest-airlines.svg',
  },
  {
    name: 'Southwest Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Southwest_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Southwest_Airlines_logo_2014.svg',
    file: 'southwest-airlines.svg',
  },
  {
    name: 'Spirit Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Spirit_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/Spirit_Airlines_logo_2014.svg',
    file: 'spirit-airlines.svg',
  },
  {
    name: 'UPS Airlines',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/UPS_Airlines',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/United_Parcel_Service_logo_2014.svg',
    file: 'ups-airlines.svg',
  },
  {
    name: 'Virgin America',
    years: '',
    country: 'Verenigde Staten',
    wiki: '/wiki/Virgin_America',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Virgin_America_logo.svg',
    file: 'virgin-america.svg',
  },
  {
    name: 'Aurigny Air Services',
    years: '',
    country: 'Verenigd Koninkrijk',
    wiki: '/wiki/Aurigny_Air_Services',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Aurigny_logo.svg',
    file: 'aurigny-air-services.svg',
  },
  {
    name: 'easyJet',
    years: '',
    country: 'Verenigd Koninkrijk',
    wiki: '/wiki/EasyJet',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/EasyJet_logo.svg',
    file: 'easyjet.svg',
  },
  {
    name: 'Virgin Atlantic Airways',
    years: '',
    country: 'Verenigd Koninkrijk',
    wiki: '/wiki/Virgin_Atlantic_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Virgin_Atlantic_logo.svg',
    file: 'virgin-atlantic-airways.svg',
  },
  {
    name: 'Belavia',
    years: '',
    country: 'Belarus',
    wiki: '/wiki/Belavia',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Belavia_logo.svg',
    file: 'belavia.svg',
  },
  {
    name: 'Fastjet',
    years: '',
    country: 'South Africa',
    wiki: '/wiki/Fastjet',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Fastjet_logo_%28without_Parrot%29.svg',
    file: 'fastjet.svg',
  },
  {
    name: 'Korean Air',
    years: '',
    country: 'South Korea',
    wiki: '/wiki/Korean_Air',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/KoreanAir_logo.svg',
    file: 'korean-air.svg',
  },
  {
    name: 'Helvetic Airways',
    years: '',
    country: 'Switzerland',
    wiki: '/wiki/Helvetic_Airways',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Helvetic_Airways_logo.svg',
    file: 'helvetic-airways.svg',
  },
];
