/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AirplaneSeatType = "business" | "economy" | "first";

export type Gender = "f" | "m" | "x";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TripType = "one_way" | "round_trip";

export interface Accommodation {
  accommodation_type_id: number;
  address_id: number;
  description: string;
  distance_to_beach: Generated<number>;
  id: Generated<number>;
  name: string;
}

export interface AccommodationAccessibility {
  id: Generated<number>;
  name: string;
}

export interface AccommodationAccommodationAccessibility {
  accommodation_accessibility_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationAccommodationCertification {
  accommodation_certification_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationAccommodationFacility {
  accommodation_facility_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationCertification {
  id: Generated<number>;
  name: string;
}

export interface AccommodationFacility {
  id: Generated<number>;
  name: string;
}

export interface AccommodationImage {
  accommodation_id: number;
  id: Generated<number>;
  image_id: number;
}

export interface AccommodationLeisure {
  accommodation_id: number;
  id: Generated<number>;
  leisure_id: number;
}

export interface AccommodationReview {
  accommodation_id: number;
  accuracy_rating: number;
  cleanliness_rating: number;
  communication_rating: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  profile_id: number;
  review: string;
  value_rating: number;
}

export interface AccommodationRoom {
  accommodation_id: number;
  id: Generated<number>;
  room_id: number;
}

export interface AccommodationType {
  id: Generated<number>;
  name: string;
}

export interface Address {
  city_id: number;
  house_number: number;
  id: Generated<number>;
  postal_code: string;
  street: string;
}

export interface Airline {
  country_id: number;
  id: Generated<number>;
  logo_src: string;
  name: string;
}

export interface Airplane {
  has_entertainment: Generated<boolean>;
  has_usb: Generated<boolean>;
  has_wifi: Generated<boolean>;
  id: Generated<number>;
  name: string;
}

export interface AirplaneSeat {
  airplane_id: number;
  bulkhead: Generated<boolean | null>;
  exit_row: Generated<boolean | null>;
  id: Generated<number>;
  row: number;
  seat: string;
  type: AirplaneSeatType;
}

export interface Airport {
  country_id: number;
  iata: string;
  icao: string;
  id: Generated<number>;
  lanes: number;
  latitude: number;
  longitude: number;
  name: string;
}

export interface City {
  id: Generated<number>;
  latitude: number;
  longitude: number;
  name: string;
  province_id: number;
}

export interface Country {
  code: string;
  id: Generated<number>;
  locales: string;
  name: string;
  native_name: string;
  risk: number;
}

export interface CountryImage {
  country_id: number;
  id: Generated<number>;
  image_id: number;
}

export interface Event {
  address_id: number;
  description: string;
  from_date: Timestamp;
  id: Generated<number>;
  image_id: number;
  leisure_id: number;
  name: string;
  price: number;
  to_date: Timestamp;
}

export interface Flight {
  airline_id: number;
  airplane_id: number;
  arrival_gate_id: number;
  arrival_planned_at: Timestamp;
  arrived_at: Timestamp | null;
  cancelled_at: Timestamp | null;
  departed_at: Timestamp | null;
  departure_gate_id: number;
  departure_planned_at: Timestamp;
  free_meals: Generated<number | null>;
  id: Generated<number>;
}

export interface Gate {
  airport_id: number;
  gate: number;
  id: Generated<number>;
  terminal: string;
}

export interface Guest {
  accommodation_id: number;
  from_date: Timestamp;
  id: Generated<number>;
  person_id: number;
  to_date: Timestamp;
}

export interface Image {
  b: number;
  h: number;
  id: Generated<number>;
  name: string;
  s: number;
  src: string;
}

export interface Leisure {
  id: Generated<number>;
  name: string;
}

export interface LeisureImage {
  id: Generated<number>;
  image_id: number;
  leisure_id: number;
}

export interface Locale {
  id: Generated<number>;
  name: string;
}

export interface Passenger {
  airplane_seat_id: number;
  boarded_at: Timestamp | null;
  checked_in_at: Timestamp | null;
  flight_id: number;
  id: Generated<number>;
  person_id: number;
  return_flight: Generated<boolean>;
  trip_id: number;
}

export interface Payment {
  amount: number;
  id: Generated<number>;
  merchant_id: string;
  payed_at: Timestamp;
  payment_method_id: number;
  profile_id: number;
  transaction_id: string;
}

export interface PaymentMethod {
  id: Generated<number>;
  name: string;
}

export interface Person {
  address_id: number;
  created_at: Generated<Timestamp>;
  date_of_birth: Timestamp | null;
  email: string;
  first_name: string;
  gender: Gender;
  id: Generated<number>;
  last_name: string;
  telephone: string | null;
}

export interface Profile {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  image_id: number;
  password: string;
  person_id: number;
}

export interface Province {
  country_id: number;
  id: Generated<number>;
  name: string;
}

export interface Room {
  floor: Generated<number | null>;
  id: Generated<number>;
  number: number;
  number_of_bathrooms: number;
  number_of_bedrooms: number;
  square_meters: number;
}

export interface RoomAccessibility {
  id: Generated<number>;
  name: string;
}

export interface RoomFacility {
  id: Generated<number>;
  name: string;
}

export interface RoomPrice {
  id: Generated<number>;
  price: number;
  room_id: number;
  week: number;
}

export interface RoomRoomAccessibility {
  id: Generated<number>;
  room_accessibility_id: number;
  room_id: number;
}

export interface RoomRoomFacility {
  id: Generated<number>;
  room_facility_id: number;
  room_id: number;
}

export interface Trip {
  booked_at: Timestamp;
  id: Generated<number>;
  payment_id: number;
  profile_id: number;
  type: TripType;
}

export interface DB {
  accommodation: Accommodation;
  accommodation_accessibility: AccommodationAccessibility;
  accommodation_accommodation_accessibility: AccommodationAccommodationAccessibility;
  accommodation_accommodation_certification: AccommodationAccommodationCertification;
  accommodation_accommodation_facility: AccommodationAccommodationFacility;
  accommodation_certification: AccommodationCertification;
  accommodation_facility: AccommodationFacility;
  accommodation_image: AccommodationImage;
  accommodation_leisure: AccommodationLeisure;
  accommodation_review: AccommodationReview;
  accommodation_room: AccommodationRoom;
  accommodation_type: AccommodationType;
  address: Address;
  airline: Airline;
  airplane: Airplane;
  airplane_seat: AirplaneSeat;
  airport: Airport;
  city: City;
  country: Country;
  country_image: CountryImage;
  event: Event;
  flight: Flight;
  gate: Gate;
  guest: Guest;
  image: Image;
  leisure: Leisure;
  leisure_image: LeisureImage;
  locale: Locale;
  passenger: Passenger;
  payment: Payment;
  payment_method: PaymentMethod;
  person: Person;
  profile: Profile;
  province: Province;
  room: Room;
  room_accessibility: RoomAccessibility;
  room_facility: RoomFacility;
  room_price: RoomPrice;
  room_room_accessibility: RoomRoomAccessibility;
  room_room_facility: RoomRoomFacility;
  trip: Trip;
}
