/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accommodation {
  accommodation_type_id: number;
  address_id: number;
  description: string;
  distance_to_beach: Generated<number>;
  id: Generated<number>;
  name: string;
  number_of_bathrooms: number;
  number_of_bedrooms: number;
  square_meters: number;
}

export interface AccommodationAccessibility {
  id: Generated<number>;
  name: string;
}

export interface AccommodationAccommodationAccessibility {
  accommodation_accessibility_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationAccommodationCertification {
  accommodation_certification_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationAccommodationFacility {
  accommodation_facility_id: number;
  accommodation_id: number;
  id: Generated<number>;
}

export interface AccommodationCertification {
  id: Generated<number>;
  name: string;
}

export interface AccommodationFacility {
  id: Generated<number>;
  name: string;
}

export interface AccommodationImage {
  accommodation_id: number;
  id: Generated<number>;
  image_id: number;
}

export interface AccommodationLeisure {
  accommodation_id: number;
  id: Generated<number>;
  leisure_id: number;
}

export interface AccommodationPrice {
  accommodation_id: number;
  id: Generated<number>;
  price: number;
  week: number;
}

export interface AccommodationReview {
  accommodation_id: number;
  accuracy_rating: number;
  cleanliness_rating: number;
  communication_rating: number;
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  profile_id: number;
  review: string;
  value_rating: number;
}

export interface AccommodationRoomAccessibility {
  accommodation_id: number;
  id: Generated<number>;
  room_accessibility_id: number;
}

export interface AccommodationRoomFacility {
  accommodation_id: number;
  id: Generated<number>;
  room_facility_id: number;
}

export interface AccommodationType {
  id: Generated<number>;
  name: string;
}

export interface Address {
  city_id: number;
  house_number: number;
  id: Generated<number>;
  postal_code: string;
  street: string;
}

export interface Airline {
  country_id: number;
  id: Generated<number>;
  logo_src: string;
  name: string;
}

export interface Airplane {
  id: Generated<number>;
  name: string;
}

export interface Airport {
  country_id: number;
  iata: string;
  icao: string;
  id: Generated<number>;
  lanes: number;
  latitude: number;
  longitude: number;
  name: string;
}

export interface City {
  id: Generated<number>;
  latitude: number;
  longitude: number;
  name: string;
  province_id: number;
}

export interface Country {
  code: string;
  id: Generated<number>;
  locales: string;
  name: string;
  native_name: string;
  risk: number;
}

export interface CountryImage {
  country_id: number;
  id: Generated<number>;
  image_id: number;
}

export interface Event {
  address_id: number;
  description: string;
  from_date: Generated<Timestamp>;
  id: Generated<number>;
  image_id: number;
  leisure_id: number;
  name: string;
  price: number;
  to_date: Generated<Timestamp>;
}

export interface Flight {
  airline_id: number;
  airplane_id: number;
  arrival_airport_id: number;
  arrival_at: Timestamp | null;
  arrival_gate: string;
  departure_airport_id: number;
  departure_at: Timestamp | null;
  departure_gate: string;
  id: Generated<number>;
  planned_arrival_at: Timestamp;
  planned_departure_at: Timestamp;
}

export interface Guest {
  date_of_birth: Timestamp | null;
  first_name: string;
  id: Generated<number>;
  last_name: string;
}

export interface Image {
  b: number;
  h: number;
  id: Generated<number>;
  name: string;
  s: number;
  src: string;
}

export interface Leisure {
  id: Generated<number>;
  name: string;
}

export interface LeisureImage {
  id: Generated<number>;
  image_id: number;
  leisure_id: number;
}

export interface Locale {
  id: Generated<number>;
  name: string;
}

export interface Passenger {
  date_of_birth: Timestamp | null;
  first_name: string;
  id: Generated<number>;
  last_name: string;
}

export interface Profile {
  address_id: number;
  date_of_birth: Timestamp | null;
  first_name: string;
  id: Generated<number>;
  image_id: number;
  last_name: string;
  telephone: string | null;
}

export interface Province {
  country_id: number;
  id: Generated<number>;
  name: string;
}

export interface RoomAccessibility {
  id: Generated<number>;
  name: string;
}

export interface RoomFacility {
  id: Generated<number>;
  name: string;
}

export interface DB {
  accommodation: Accommodation;
  accommodation_accessibility: AccommodationAccessibility;
  accommodation_accommodation_accessibility: AccommodationAccommodationAccessibility;
  accommodation_accommodation_certification: AccommodationAccommodationCertification;
  accommodation_accommodation_facility: AccommodationAccommodationFacility;
  accommodation_certification: AccommodationCertification;
  accommodation_facility: AccommodationFacility;
  accommodation_image: AccommodationImage;
  accommodation_leisure: AccommodationLeisure;
  accommodation_price: AccommodationPrice;
  accommodation_review: AccommodationReview;
  accommodation_room_accessibility: AccommodationRoomAccessibility;
  accommodation_room_facility: AccommodationRoomFacility;
  accommodation_type: AccommodationType;
  address: Address;
  airline: Airline;
  airplane: Airplane;
  airport: Airport;
  city: City;
  country: Country;
  country_image: CountryImage;
  event: Event;
  flight: Flight;
  guest: Guest;
  image: Image;
  leisure: Leisure;
  leisure_image: LeisureImage;
  locale: Locale;
  passenger: Passenger;
  profile: Profile;
  province: Province;
  room_accessibility: RoomAccessibility;
  room_facility: RoomFacility;
}
